In [150]:
import numpy as np
import random
import pandas as pd

In [151]:
np.random.seed(42)
df1 = pd.DataFrame(np.random.rand(2048,20))
df1

0         1         2         3         4         5         6   \
0     0.374540  0.950714  0.731994  0.598658  0.156019  0.155995  0.058084   
1     0.611853  0.139494  0.292145  0.366362  0.456070  0.785176  0.199674   
2     0.122038  0.495177  0.034389  0.909320  0.258780  0.662522  0.311711   
3     0.388677  0.271349  0.828738  0.356753  0.280935  0.542696  0.140924   
4     0.863103  0.623298  0.330898  0.063558  0.310982  0.325183  0.729606   
...        ...       ...       ...       ...       ...       ...       ...   
2043  0.003786  0.380262  0.290487  0.217909  0.251589  0.942365  0.486317   
2044  0.987196  0.697027  0.321402  0.151294  0.392531  0.220566  0.494153   
2045  0.166670  0.584471  0.017257  0.196249  0.002529  0.180536  0.474757   
2046  0.144081  0.642863  0.520053  0.028184  0.399243  0.784788  0.555424   
2047  0.232617  0.325350  0.710128  0.238393  0.208187  0.703473  0.880595   

            7         8         9         10        11        12        13  \
0     0.866176  0.601115  0.708073  0.020584  0.969910  0.832443  0.212339   
1     0.514234  0.592415  0.046450  0.607545  0.170524  0.065052  0.948886   
2     0.520068  0.546710  0.184854  0.969585  0.775133  0.939499  0.894827   
3     0.802197  0.074551  0.986887  0.772245  0.198716  0.005522  0.815461   
4     0.637557  0.887213  0.472215  0.119594  0.713245  0.760785  0.561277   
...        ...       ...       ...       ...       ...       ...       ...   
2043  0.847709  0.214217  0.174404  0.888790  0.495705  0.895152  0.063029   
2044  0.781893  0.660130  0.435935  0.118944  0.957157  0.270371  0.277835   
2045  0.393324  0.369297  0.830953  0.674996  0.936432  0.445341  0.272230   
2046  0.282041  0.928642  0.237779  0.252736  0.354639  0.894538  0.507625   
2047  0.075017  0.445908  0.607175  0.676277  0.996196  0.682692  0.620154   

            14        15        16        17        18        19  
0     0.181825  0.183405  0.304242  0.524756  0.431945  0.291229  
1     0.965632  0.808397  0.304614  0.097672  0.684233  0.440152  
2     0.597900  0.921874  0.088493  0.195983  0.045227  0.325330  
3     0.706857  0.729007  0.771270  0.074045  0.358466  0.115869  
4     0.770967  0.493796  0.522733  0.427541  0.025419  0.107891  
...        ...       ...       ...       ...       ...       ...  
2043  0.916436  0.415445  0.155370  0.683383  0.796903  0.047375  
2044  0.645502  0.770510  0.984153  0.969164  0.913761  0.435314  
2045  0.122685  0.672027  0.841741  0.183739  0.878753  0.526276  
2046  0.682179  0.976264  0.783296  0.172600  0.788354  0.748337  
2047  0.989734  0.060668  0.074437  0.560683  0.358665  0.096698  

[2048 rows x 20 columns]

In [152]:
np.random.seed(38)
df2 = pd.DataFrame(10*np.random.rand(2048,20))
df2

0         1         2         3         4         5         6   \
0     3.847731  8.597078  9.441996  7.028249  6.336341  6.059613  2.001268   
1     9.603672  8.581442  3.091764  5.497211  6.546784  9.508587  9.747696   
2     4.430334  5.983994  1.271930  8.118450  2.178787  0.904260  1.211678   
3     4.172737  2.907360  6.893273  9.198399  5.793105  6.701522  6.439989   
4     4.166563  7.456686  0.326819  0.198535  7.370736  5.160968  2.975294   
...        ...       ...       ...       ...       ...       ...       ...   
2043  6.235817  6.436419  7.394542  7.496877  2.648512  5.469371  7.920594   
2044  4.802307  5.784105  8.693323  1.968789  7.933178  5.272510  0.516305   
2045  5.755876  6.005353  2.760837  0.489789  6.248765  5.271895  9.110376   
2046  9.756057  8.310655  3.227298  1.699296  2.954398  3.498864  3.125935   
2047  3.788500  0.489200  5.809020  2.563627  7.383502  4.801021  5.841687   

            7         8         9         10        11        12        13  \
0     3.873879  2.589832  0.746073  2.809570  4.384342  4.832490  8.684895   
1     4.485347  7.992729  7.283536  0.881456  7.930346  9.231643  6.149062   
2     9.919985  3.239919  4.017410  4.787376  4.177047  2.948129  5.695074   
3     6.625088  3.912486  7.287966  6.360186  4.580688  0.271525  5.262847   
4     5.428181  8.496259  3.601186  8.734662  8.551367  2.223294  6.505204   
...        ...       ...       ...       ...       ...       ...       ...   
2043  3.529882  8.005387  3.561296  6.253828  3.686864  5.308369  3.473054   
2044  7.051076  5.271530  4.162552  8.964973  3.011167  7.251785  1.602414   
2045  6.776783  9.636407  6.256474  7.665654  3.113857  1.191996  3.401281   
2046  5.883301  1.522689  1.161621  6.857537  4.821688  8.649464  5.672055   
2047  4.377395  5.547003  4.622797  3.992563  4.867656  9.610997  3.545103   

            14        15        16        17        18        19  
0     5.296294  5.622631  4.710553  6.888420  5.048286  8.231758  
1     2.107859  2.416412  4.131790  7.291894  0.150904  1.842787  
2     3.632858  2.500698  4.418732  6.012679  3.294576  6.483155  
3     4.556715  6.417756  5.439705  9.675948  7.879194  6.157460  
4     9.496075  6.769389  5.101022  2.493281  1.473121  4.076523  
...        ...       ...       ...       ...       ...       ...  
2043  8.370744  6.730434  2.909277  5.702689  2.521041  8.024738  
2044  3.297947  0.337252  2.802995  0.670098  3.764093  7.019006  
2045  8.584520  8.602565  3.628446  0.887368  8.806179  7.916173  
2046  9.428825  8.903392  7.596135  7.311443  1.302034  8.422089  
2047  0.083054  1.139135  1.145672  0.040160  0.720972  4.904411  

[2048 rows x 20 columns]

In [153]:
df1.to_csv("EEM1.csv")
df2.to_csv("EEM10.csv")

In [154]:
x_train = [df1, df2]
y_train = [1, 10]

In [155]:
x_train = np.array(x_train)
x_train.reshape(2, -1).shape
# np.array(df1).flatten().shape

(2, 40960)

In [156]:
x_train.reshape(2,-1).shape
np.array(y_train).shape

(2,)

In [157]:
from sklearn.linear_model import LinearRegression
logreg = LinearRegression().fit(x_train.reshape(2,-1), np.array(y_train))
print("Training set score : {:.3f}".format(logreg.score(x_train.reshape(2,-1), y_train)))


Training set score : 1.000


In [158]:
logreg.predict(np.array(df2).reshape(1, -1))

array([10.])

In [159]:
logreg.coef_

array([ 2.65978625e-05,  5.85562204e-05,  6.67016128e-05, ...,
       -3.98618975e-06,  2.77456470e-06,  3.68176953e-05])

In [160]:
logreg.intercept_

0.3198563821554581

In [165]:
np.random.seed(9)
df3 = pd.DataFrame(10*np.random.rand(2048,20))
df3

0         1         2         3         4         5         6   \
0     0.103742  5.018746  4.957733  1.338295  1.421111  2.185587  4.185082   
1     3.864772  6.944387  8.248705  4.656685  9.405244  8.037398  9.833592   
2     6.105377  4.962817  4.779740  4.355555  8.704083  1.873586  6.876741   
3     4.844985  6.977364  8.011564  2.667744  9.094762  0.228669  3.751228   
4     7.347658  5.562165  3.026306  9.707982  2.248426  1.387692  6.149325   
...        ...       ...       ...       ...       ...       ...       ...   
2043  3.407586  1.739422  9.010440  0.723304  2.919242  5.840751  9.759569   
2044  4.144771  0.877474  8.854070  1.196845  1.204729  1.943848  2.244015   
2045  7.759594  5.335995  8.155348  3.906683  5.522401  4.268082  3.844016   
2046  4.684321  2.580087  4.897066  0.017395  1.002500  6.084585  9.677469   
2047  7.616409  1.983511  4.440746  3.017187  3.186840  4.537955  8.389868   

            7         8         9         10        11        12        13  \
0     2.481012  0.840597  3.454986  1.667763  8.785591  9.509640  0.387484   
1     1.696363  5.210847  9.455174  6.495405  8.608319  9.708460  1.855417   
2     7.035292  9.252001  0.394548  6.471167  6.380540  4.616977  0.530594   
3     1.996333  3.428052  4.441123  4.981396  4.143463  2.142560  2.166397   
4     4.919289  1.831527  1.093105  5.395755  2.892993  1.030541  4.906015   
...        ...       ...       ...       ...       ...       ...       ...   
2043  2.755711  2.352558  8.366534  9.568978  7.314227  2.894500  9.393601   
2044  4.744325  3.760661  8.330628  5.706873  3.483289  7.607017  2.878772   
2045  8.379555  4.565636  2.040798  0.554809  6.087729  3.516084  1.155270   
2046  3.025802  1.216689  6.372439  2.991483  7.882099  8.174236  7.422495   
2047  1.598938  6.267865  3.361308  9.817623  0.339391  3.332622  6.752246   

            14        15        16        17        18        19  
0     6.991074  5.727598  8.980071  6.668990  5.478378  7.024274  
1     2.431157  8.734008  9.062773  7.582780  3.469020  4.635347  
2     0.385709  1.695314  7.945479  1.626060  1.387387  3.529170  
3     2.323071  7.290856  4.159187  5.838982  4.943366  4.300468  
4     6.320917  0.379692  5.001079  0.835434  7.913182  7.580360  
...        ...       ...       ...       ...       ...       ...  
2043  3.159348  2.479384  7.119502  9.058258  6.043762  5.295970  
2044  4.897214  2.746302  5.256056  5.644111  3.758068  0.724544  
2045  3.455669  0.485682  8.276560  3.743953  3.119551  2.671151  
2046  0.477424  7.410990  6.691375  1.106337  0.168505  5.240060  
2047  0.290031  9.565952  8.535293  4.329799  8.458960  3.545674  

[2048 rows x 20 columns]

In [166]:
logreg.predict(np.array(df3).reshape(1, -1))

array([7.41503614])